### ISSUE TITLE
how to use the samples

### ISSUE THREAD

**Issue by jmecosta** [microsoft/cpp-build-insights-samples#3]
hi,

i would like to try the samples. but im lost with documentation

![image](https://user-images.githubusercontent.com/1041352/82494595-80175f80-9af2-11ea-9e98-90df96ac2190.png)

the etl contins all needed file stuff etc! are the exes supose to do something?

**Comment by kevcadieux** [comment]
Hello Jorge, did you stop the trace with the /stopnoanalyze switch?

**Comment by kevinmoran** [comment]
> Hello Jorge, did you stop the trace with the /stopnoanalyze switch?

Thanks for posting this here, but could this be detected by the samples and have a message output, e.g. "Cannot analyze file, please use /stopnoanalyze switch when ending traces"? Or add a troubleshooting section to the README? Getting completely blank output from all the samples and having to dig through the closed issues to find this is a bit of an adventure!

Also I'm surprised only non-analyzed files can be used... Does analyzing a trace destroy some of the data so that they can't be used for the samples?
